# Generated by Django 4.2.6 on 2023-12-21 08:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Articulo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("codigo_sku", models.CharField(max_length=25)),
                ("descripcion", models.CharField(max_length=150)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("cantidad_unidad_medida", models.IntegerField(default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CanalCliente",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("canal_cliente_descripcion", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Clientes",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nro_documento", models.CharField(max_length=12)),
                ("nombre_razon_social", models.CharField(max_length=150)),
                ("direccion", models.CharField(max_length=150)),
                (
                    "canal_cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finals.canalcliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CondicionVentas",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("descripcion", models.CharField(max_length=100)),
                ("genera_credito", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nro_documento", models.CharField(max_length=11)),
                ("razon_social", models.CharField(max_length=150)),
                ("direccion", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="GruposProveedor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("codigo_grupo", models.CharField(max_length=15)),
                ("grupo_descripcion", models.CharField(max_length=100)),
                ("activo", models.BooleanField()),
                ("responsable_grupo", models.CharField(max_length=25)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="finals.empresa"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LineasArticulos",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("codigo_linea", models.CharField(max_length=15)),
                ("linea_descripcion", models.CharField(max_length=100)),
                ("activo", models.BooleanField()),
                ("responsable_linea", models.CharField(max_length=25)),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finals.gruposproveedor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Marcas",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("codigo_marca", models.CharField(max_length=14)),
                ("marca_nombre", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Promocion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo_promocion",
                    models.CharField(
                        choices=[
                            ("caso_1", "Descuento por Cantidad Comprada (1)"),
                            ("caso_2", "Bonificación por Monto Total (2)"),
                            (
                                "caso_3",
                                "Bonitifacion por productos y presentaciones(3)",
                            ),
                            ("caso_4", "Descuento por Rango de Cantidad (4)"),
                            ("caso_5", "Descuento por Rango de Monto (5)"),
                            ("caso_7", "Bonificación por escalas (7)"),
                            ("caso_8", "Bonificación por Cantidad Comprada gratis(8)"),
                            ("caso_9", "Bonificación y descuento por rango(9)"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("fecha_inicio", models.DateTimeField(blank=True, null=True)),
                ("fecha_fin", models.DateTimeField(blank=True, null=True)),
                (
                    "cantidad_minima_compra",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "cantidad_maxima_compra",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "monto_minimo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "monto_maximo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "porcentaje_descuento",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "unidades_bonificadas",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                ("activo", models.BooleanField(default=False)),
                (
                    "articulo_aplicable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos_aplicables",
                        to="finals.articulo",
                    ),
                ),
                (
                    "articulo_bonificacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos_bonificacion",
                        to="finals.articulo",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promociones",
                        to="finals.gruposproveedor",
                    ),
                ),
                (
                    "tipo_cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promociones",
                        to="finals.canalcliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TipoPedido",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tipo_pedido_nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TiposIdentificacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tipo_identificacion_nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="UnidadesMedida",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("unidad_nombre", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Usuarios",
            fields=[
                ("username", models.CharField(max_length=25)),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=255)),
                ("password", models.CharField(max_length=100)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="Vendedor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("vendedor_codigo", models.CharField(max_length=15)),
                ("nro_documento", models.CharField(max_length=11)),
                ("nombres", models.CharField(max_length=150)),
                ("direccion", models.CharField(max_length=150)),
                ("correo_electronico", models.CharField(max_length=255)),
                ("nro_movil", models.CharField(max_length=15)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="finals.empresa"
                    ),
                ),
                (
                    "tipo_identificacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finals.tiposidentificacion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sucursal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre_comercial", models.CharField(max_length=150)),
                ("direccion", models.CharField(max_length=150)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="finals.empresa"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SublineasArticulos",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("codigo_sublinea", models.CharField(max_length=15)),
                ("sublinea_descripcion", models.CharField(max_length=100)),
                ("estado", models.BooleanField()),
                (
                    "linea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finals.lineasarticulos",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Promocion_articulos_bonificados",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cantidad_articulo",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "articulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finals.articulo",
                    ),
                ),
                (
                    "promocion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finals.promocion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Promocion_articulos_asociados",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cantidad_articulo",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "articulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finals.articulo",
                    ),
                ),
                (
                    "promocion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finals.promocion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotasVenta",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fecha_pedido",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("plazo", models.IntegerField()),
                (
                    "total_pedido",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, null=True
                    ),
                ),
                ("nro_pedido", models.IntegerField()),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finals.clientes",
                    ),
                ),
                (
                    "condicion_venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finals.condicionventas",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="finals.empresa"
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finals.sucursal",
                    ),
                ),
                (
                    "tipo_pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finals.tipopedido",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemsNotaVenta",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nro_item", models.IntegerField(default=0)),
                ("descripcion", models.JSONField(null=True)),
                (
                    "cantidad",
                    models.DecimalField(decimal_places=2, default=1, max_digits=12),
                ),
                (
                    "total_item_bruto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "factor_descuento",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "descuento_unitario",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_item",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("es_bonificacion", models.BooleanField(default=False)),
                (
                    "articulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finals.articulo",
                    ),
                ),
                (
                    "nota_venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finals.notasventa",
                    ),
                ),
                (
                    "referencia_bonificacion",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finals.itemsnotaventa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DescuentoNotaVenta",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "porcentaje_descuento",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "nota_venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finals.notasventa",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="articulo",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="finals.empresa"
            ),
        ),
        migrations.AddField(
            model_name="articulo",
            name="grupo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="finals.gruposproveedor"
            ),
        ),
        migrations.AddField(
            model_name="articulo",
            name="linea",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="finals.lineasarticulos"
            ),
        ),
        migrations.AddField(
            model_name="articulo",
            name="marca",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="finals.marcas"
            ),
        ),
        migrations.AddField(
            model_name="articulo",
            name="sublinea",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="finals.sublineasarticulos",
            ),
        ),
        migrations.AddField(
            model_name="articulo",
            name="unidad_medida",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="finals.unidadesmedida"
            ),
        ),
    ]
