# Generated by Django 4.2.7 on 2023-11-21 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finals', '0002_categoria_produc_venta_categoria_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produc',
            name='fechaP',
        ),
    ]
