# Generated by Django 4.2.7 on 2023-11-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finals', '0003_remove_produc_fechap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produc',
            name='codigo',
            field=models.CharField(max_length=12),
        ),
    ]
