# Generated by Django 4.2.7 on 2023-11-21 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finals', '0004_alter_produc_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Produc',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
