# Generated by Django 4.2.7 on 2023-11-22 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finals', '0006_canalcliente_clientes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='canal_cliente_id',
            new_name='canal_cliente',
        ),
    ]
