# Generated by Django 4.2.7 on 2023-11-26 20:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('finals', '0007_rename_canal_cliente_id_clientes_canal_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionVentas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('genera_credito', models.CharField(max_length=10)),
            ],
        ),
    ]
