# Generated by Django 4.2.7 on 2023-11-27 01:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('finals', '0008_condicionventas'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_pedido_nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TiposIdentificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_identificacion_nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendedor_codigo', models.CharField(max_length=15)),
                ('nro_documento', models.CharField(max_length=11)),
                ('nombres', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=150)),
                ('correo_electronico', models.CharField(max_length=255)),
                ('nro_movil', models.CharField(max_length=15)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finals.empresa')),
                ('tipo_identificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finals.tiposidentificacion')),
            ],
        ),
    ]
