# Generated by Django 4.2.6 on 2023-11-27 02:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('finals', '0009_tipopedido_tiposidentificacion_vendedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotasVenta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nro_pedido', models.CharField(max_length=25)),
                ('fecha_pedido', models.DateTimeField()),
                ('plazo', models.IntegerField()),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('Pasaporte', 'Pasaporte')], max_length=10)),
                ('total_pedido', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finals.clientes')),
                ('condicion_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finals.condicionventas')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finals.empresa')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finals.sucursal')),
                ('tipo_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finals.tipopedido')),
            ],
        ),
    ]
