# Generated by Django 4.2.6 on 2023-11-27 04:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('finals', '0010_notasventa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsNotaVenta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nro_item', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_item_bruto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('factor_descuento', models.DecimalField(decimal_places=3, max_digits=12)),
                ('descuento_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_item', models.DecimalField(decimal_places=2, max_digits=12)),
                ('es_bonificacion', models.CharField(max_length=1)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finals.articulo')),
                ('nota_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finals.notasventa')),
            ],
        ),
    ]
