# Generated by Django 4.2.6 on 2023-11-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finals', '0012_alter_itemsnotaventa_es_bonificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsnotaventa',
            name='precio_unitario',
        ),
        migrations.AddField(
            model_name='articulo',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='itemsnotaventa',
            name='descuento_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='itemsnotaventa',
            name='factor_descuento',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='itemsnotaventa',
            name='nro_item',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemsnotaventa',
            name='total_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='itemsnotaventa',
            name='total_item_bruto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
