# Generated by Django 4.2.6 on 2023-11-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finals', '0014_itemsnotaventa_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsnotaventa',
            name='descripcion',
            field=models.JSONField(null=True),
        ),
    ]
