# Generated by Django 4.2.6 on 2023-12-04 03:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('finals', '0015_alter_itemsnotaventa_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('activo', models.BooleanField()),
                ('descripcion_condicion', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('codigo_sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='finals.articulo')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='finals.lineasarticulos')),
                ('sublinea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='finals.sublineasarticulos')),
                ('tipo_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='finals.canalcliente')),
                ('tipo_formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='finals.gruposproveedor')),
            ],
        ),
    ]
