# Generated by Django 4.2.6 on 2023-12-09 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finals', '0017_alter_promocion_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='activo',
            field=models.BooleanField(),
        ),
    ]
