# Generated by Django 4.2.6 on 2023-12-11 03:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finals", "0018_alter_promocion_activo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promocion",
            name="descripcion_condicion",
        ),
        migrations.RemoveField(
            model_name="promocion",
            name="linea",
        ),
        migrations.RemoveField(
            model_name="promocion",
            name="sublinea",
        ),
        migrations.RemoveField(
            model_name="promocion",
            name="tipo_formula",
        ),
    ]
