# Generated by Django 4.2.6 on 2023-12-11 04:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finals", "0019_remove_promocion_descripcion_condicion_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="promocion",
            old_name="codigo_sku",
            new_name="articulo",
        ),
    ]
