# Generated by Django 4.2.6 on 2023-12-13 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("finals", "0021_remove_promocion_articulo_remove_promocion_cantidad_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productosaplicables",
            name="articulo",
        ),
        migrations.AddField(
            model_name="productosaplicables",
            name="articulo_aplicable",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productos_aplicables",
                to="finals.articulo",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productosaplicables",
            name="articulo_bonificacion",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productos_bonificacion",
                to="finals.articulo",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productosaplicables",
            name="cantidad",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
