# Generated by Django 4.2.6 on 2023-12-13 05:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "finals",
            "0023_rename_cantidad_productosaplicables_cantidad_bonificacion_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productosaplicables",
            name="cantidad_bonificacion",
        ),
    ]
