# Generated by Django 4.2.6 on 2023-12-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finals", "0025_promocion_articulo_aplicable_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promocion",
            name="porcentaje_descuento",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="promocion",
            name="tipo_promocion",
            field=models.CharField(
                choices=[
                    ("caso_1", "Descuento por Cantidad Comprada (caso 1)"),
                    ("caso_2", "Bonificación por Monto Total (caso 2)"),
                    ("Descuento_Proveedor", "Descuento por Proveedor"),
                    ("Descuento_Rango", "Descuento por Rango de Compra"),
                    ("Descuento_Monto", "Descuento por Monto Total"),
                    ("Bonificacion", "Bonificación"),
                    ("Bonificacion_Cantidad", "Bonificación por Cantidad Comprada"),
                    ("Bonificacion_Proveedor", "Bonificación por Proveedor"),
                    ("Bonificacion_Rango", "Bonificación por Rango de Compra"),
                    ("Regalo", "Regalo con Compra"),
                    ("Regalo_Cantidad", "Regalo por Cantidad Comprada"),
                    ("Regalo_Monto", "Regalo por Monto Total"),
                    ("Regalo_Proveedor", "Regalo por Proveedor"),
                    ("Regalo_Rango", "Regalo por Rango de Compra"),
                ],
                max_length=50,
            ),
        ),
    ]
