# Generated by Django 4.2.6 on 2023-12-13 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("finals", "0026_alter_promocion_porcentaje_descuento_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promocion",
            name="articulo_aplicable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productos_aplicables",
                to="finals.articulo",
            ),
        ),
        migrations.AlterField(
            model_name="promocion",
            name="articulo_bonificacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productos_bonificacion",
                to="finals.articulo",
            ),
        ),
        migrations.AlterField(
            model_name="promocion",
            name="tipo_promocion",
            field=models.CharField(
                choices=[
                    ("caso_1", "Descuento por Cantidad Comprada (1)"),
                    ("caso_2", "Bonificación por Monto Total (2)"),
                    ("caso_3", "Bonitifacion por productos y presentaciones(3)"),
                    ("Descuento_Rango", "Descuento por Rango de Compra"),
                    ("Descuento_Monto", "Descuento por Monto Total"),
                    ("Bonificacion", "Bonificación"),
                    ("Bonificacion_Cantidad", "Bonificación por Cantidad Comprada"),
                    ("Bonificacion_Proveedor", "Bonificación por Proveedor"),
                    ("Bonificacion_Rango", "Bonificación por Rango de Compra"),
                    ("Regalo", "Regalo con Compra"),
                    ("Regalo_Cantidad", "Regalo por Cantidad Comprada"),
                    ("Regalo_Monto", "Regalo por Monto Total"),
                    ("Regalo_Proveedor", "Regalo por Proveedor"),
                    ("Regalo_Rango", "Regalo por Rango de Compra"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Promocion_articulos_asociados",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "articulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finals.articulo",
                    ),
                ),
                (
                    "promocion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finals.promocion",
                    ),
                ),
            ],
        ),
    ]
