# Generated by Django 4.2.6 on 2023-12-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finals", "0027_alter_promocion_articulo_aplicable_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unidadesmedida",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
