# Generated by Django 4.2.6 on 2023-12-14 03:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("finals", "0028_alter_unidadesmedida_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promocion_articulos_asociados",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="unidadesmedida",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
