# Generated by Django 4.2.6 on 2023-12-14 03:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finals", "0029_alter_promocion_articulos_asociados_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articulo",
            name="factor_compra",
        ),
        migrations.RemoveField(
            model_name="articulo",
            name="factor_reparto",
        ),
    ]
