# Generated by Django 4.2.6 on 2023-12-14 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finals", "0031_promocion_articulos_asociados_cantidad_articulo"),
    ]

    operations = [
        migrations.AddField(
            model_name="promocion",
            name="cantidad_maxima_compra",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="promocion",
            name="tipo_promocion",
            field=models.CharField(
                choices=[
                    ("caso_1", "Descuento por Cantidad Comprada (1)"),
                    ("caso_2", "Bonificación por Monto Total (2)"),
                    ("caso_3", "Bonitifacion por productos y presentaciones(3)"),
                    ("caso_4", "Descuento por Rango de Compra (4)"),
                    ("Descuento_Monto", "Descuento por Monto Total"),
                    ("Bonificacion", "Bonificación"),
                    ("Bonificacion_Cantidad", "Bonificación por Cantidad Comprada"),
                    ("Bonificacion_Proveedor", "Bonificación por Proveedor"),
                    ("Bonificacion_Rango", "Bonificación por Rango de Compra"),
                    ("Regalo", "Regalo con Compra"),
                    ("Regalo_Cantidad", "Regalo por Cantidad Comprada"),
                    ("Regalo_Monto", "Regalo por Monto Total"),
                    ("Regalo_Proveedor", "Regalo por Proveedor"),
                    ("Regalo_Rango", "Regalo por Rango de Compra"),
                ],
                max_length=50,
            ),
        ),
    ]
