# Generated by Django 4.2.6 on 2023-12-14 05:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("finals", "0032_promocion_cantidad_maxima_compra_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promocion",
            name="condiciones",
        ),
        migrations.RemoveField(
            model_name="promocion",
            name="descuentos",
        ),
        migrations.RemoveField(
            model_name="promocion",
            name="formula",
        ),
        migrations.AlterField(
            model_name="promocion",
            name="porcentaje_descuento",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="promocion",
            name="tipo_promocion",
            field=models.CharField(
                choices=[
                    ("caso_1", "Descuento por Cantidad Comprada (1)"),
                    ("caso_2", "Bonificación por Monto Total (2)"),
                    ("caso_3", "Bonitifacion por productos y presentaciones(3)"),
                    ("caso_4", "Descuento por Rango de Cantidad (4)"),
                    ("caso_5", "Descuento por Rango de Monto (5)"),
                    ("caso_7", "Bonificación por escalas (7)"),
                    ("caso_8", "Bonificación por Cantidad Comprada gratis(8)"),
                    ("caso_9", "Bonificación y descuento por rango(9)"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Promocion_articulos_bonificados",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cantidad_articulo",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "articulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finals.articulo",
                    ),
                ),
                (
                    "promocion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finals.promocion",
                    ),
                ),
            ],
        ),
    ]
