# Generated by Django 4.2.6 on 2023-12-14 07:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("finals", "0034_alter_promocion_monto_maximo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notasventa",
            name="nro_pedido",
        ),
        migrations.RemoveField(
            model_name="notasventa",
            name="tipo_documento",
        ),
        migrations.AlterField(
            model_name="notasventa",
            name="fecha_pedido",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="notasventa",
            name="total_pedido",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
    ]
