# Generated by Django 4.2.6 on 2023-12-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finals", "0035_remove_notasventa_nro_pedido_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notasventa",
            name="nro_pedido",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
