# Generated by Django 4.1.9 on 2023-12-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finals", "0036_notasventa_nro_pedido"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemsnotaventa",
            name="es_bonificacion",
            field=models.BooleanField(),
        ),
    ]
