# Generated by Django 4.2.6 on 2023-12-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finals', '0038_alter_itemsnotaventa_es_bonificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsnotaventa',
            name='factor_descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
